### ISSUE TITLE
Cannot compile for MKR WAN 1300

### ISSUE THREAD

**Issue by TheOldBrick** [cyborg5/IRLib2#111]
In Arduino IDE, a very simple sketch that uses IRLib2 can't compile for Arduino MKR WAN 1300.

You can find the sketch and the error messages here: [Can't compile IRLib2 for MKR WAN 1300.zip](https://drive.google.com/file/d/1MrkuRc6v9SdlagqhMC4bL0tK3NpBjrAj/view?usp=sharing)

**Comment by cyborg5** [comment]
That board is not supported
