### ISSUE TITLE
Can I use the library for multiple receivers on one arduino

### ISSUE THREAD

**Issue by pvdw0310** [cyborg5/IRLib2#123]
Hi, This is a very fast decode library and I would like to use that library for multiple receivers on one arduino? I need to read only 1 protocol but about 5 receivers with a distance of about 0.5meter from each other. I make a bridge with the receivers on, and if a model racing car, that sends an unique ircode,  is passing, the receiver above is detecting that code. So each receiver detects his code from the passing Ir sender .

Please advice what i can do to let it work.
Many Thanks

**Comment by cyborg5** [comment]
This library really isn't very well set up for multiple receivers. There is a circuit diagram in the users manual that shows how you can connect them through a logic gate but if the same signal hits on small receivers I'm not sure it would work.
