### ISSUE TITLE
Cannot compile example analyse.ino

### ISSUE THREAD

**Issue by willbelr** [cyborg5/IRLib2#18]
I use Arch linux, with;
arduino 1.8.0
arduino-avr-core 1.6.17
arduino-builder 1.3.24
arduino-mk 1.5.2
avr-gcc 6.3.0
avrdude 6.3.2

I could not compile the code using Arduino IDE:
> lto1: internal compiler error: in lto_output_varpool_node, at lto-cgraph.c:583
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See <http://gcc.gnu.org/bugs.html> for instructions.
> lto-wrapper: fatal error: /usr/bin/avr-gcc returned 1 exit status
> compilation terminated.
> /usr/bin/avr-ld: error: lto-wrapper failed
> collect2: error: ld returned 1 exit status
> exit status 1
> Error compiling for board Arduino/Genuino Uno.

nor Make:
> /usr/share/arduino/hardware/tools/avr/bin/avr-gcc-ar rcs build-uno/libcore.a  build-uno/core/wiring.c.o  build-uno/core/WInterrupts.c.o  build-uno/core/wiring_digital.c.o  build-uno/core/hooks.c.o  build-uno/core/wiring_pulse.c.o  build-uno/core/wiring_analog.c.o  build-uno/core/wiring_shift.c.o  build-uno/core/IPAddress.cpp.o  build-uno/core/new.cpp.o  build-uno/core/abi.cpp.o  build-uno/core/WString.cpp.o  build-uno/core/Tone.cpp.o  build-uno/core/WMath.cpp.o  build-uno/core/HardwareSerial0.cpp.o  build-uno/core/Print.cpp.o  build-uno/core/Stream.cpp.o  build-uno/core/HardwareSerial2.cpp.o  build-uno/core/USBCore.cpp.o  build-uno/core/PluggableUSB.cpp.o  build-uno/core/main.cpp.o  build-uno/core/HardwareSerial.cpp.o  build-uno/core/HardwareSerial1.cpp.o  build-uno/core/CDC.cpp.o  build-uno/core/HardwareSerial3.cpp.o  build-uno/core/wiring_pulse.S.o       build-uno/userlibs/IRLib2/IRLibRecvBase.cpp.o build-uno/userlibs/IRLib2/IRLibDecodeBase.cpp.o build-uno/userlibs/IRLib2/IRLibRecvLoop.cpp.o build-uno/userlibs/IRLibProtocols/IRLibSAMD21.cpp.o build-uno/userlibs/IRLibProtocols/IRLibProtocols.cpp.o build-uno/userlibs/IRLibProtocols/IRLibHardware.cpp.o build-uno/userlibs/IRLibProtocols/IRLibSendBase.cpp.o build-uno/userlibs/IRLibRecvPCI/IRLibRecvPCI.cpp.o build-uno/userlibs/arduino/IPAddress.cpp.o build-uno/userlibs/arduino/new.cpp.o build-uno/userlibs/arduino/abi.cpp.o build-uno/userlibs/arduino/WString.cpp.o build-uno/userlibs/arduino/Tone.cpp.o build-uno/userlibs/arduino/WMath.cpp.o build-uno/userlibs/arduino/HardwareSerial0.cpp.o build-uno/userlibs/arduino/Print.cpp.o build-uno/userlibs/arduino/Stream.cpp.o build-uno/userlibs/arduino/HardwareSerial2.cpp.o build-uno/userlibs/arduino/USBCore.cpp.o build-uno/userlibs/arduino/PluggableUSB.cpp.o build-uno/userlibs/arduino/main.cpp.o build-uno/userlibs/arduino/HardwareSerial.cpp.o build-uno/userlibs/arduino/HardwareSerial1.cpp.o build-uno/userlibs/arduino/CDC.cpp.o build-uno/userlibs/arduino/HardwareSerial3.cpp.o build-uno/userlibs/arduino/wiring.c.o build-uno/userlibs/arduino/WInterrupts.c.o build-uno/userlibs/arduino/wiring_digital.c.o build-uno/userlibs/arduino/hooks.c.o build-uno/userlibs/arduino/wiring_pulse.c.o build-uno/userlibs/arduino/wiring_analog.c.o build-uno/userlibs/arduino/wiring_shift.c.o build-uno/userlibs/arduino/wiring_pulse.S.o
> /usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -Wl,--gc-sections -Os -flto -fuse-linker-plugin -o build-uno/analyse.elf build-uno/analyze.cpp.o build-uno/libcore.a   -lc -lm 
> lto1: internal compiler error: Segmentation fault
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See <http://gcc.gnu.org/bugs.html> for instructions.
> lto-wrapper: fatal error: /usr/share/arduino/hardware/tools/avr/bin/avr-gcc returned 1 exit status
> compilation terminated.
> /usr/bin/avr-ld: error: lto-wrapper failed
> collect2: error: ld returned 1 exit status
> make: *** [/usr/share/arduino/Arduino.mk:1443: build-uno/analyse.elf] Error 1

make -d
>      Finished prerequisites of target file 'build-uno/analyse.elf'.
>     Must remake target 'build-uno/analyse.elf'.
> /usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -Wl,--gc-sections -Os -flto -fuse-linker-plugin -o build-uno/analyse.elf build-uno/analyze.cpp.o build-uno/libcore.a   -lc -lm 
> Putting child 0x1f5f6d0 (build-uno/analyse.elf) PID 20633 on the chain.
> Live child 0x1f5f6d0 (build-uno/analyse.elf) PID 20633 
> lto1: internal compiler error: Segmentation fault
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See <http://gcc.gnu.org/bugs.html> for instructions.
> lto-wrapper: fatal error: /usr/share/arduino/hardware/tools/avr/bin/avr-gcc returned 1 exit status
> compilation terminated.
> /usr/bin/avr-ld: error: lto-wrapper failed
> collect2: error: ld returned 1 exit status
> Reaping losing child 0x1f5f6d0 PID 20633 
> make: *** [/usr/share/arduino/Arduino.mk:1443: build-uno/analyse.elf] Error 1
> Removing child 0x1f5f6d0 PID 20633 from chain.

It used to work earlier this year, I tried to downgrade avr-gcc down to v5, but I ended up using another library to get the IR code.. I can compile some example code (ie send.ino), but most seem broken due to various errors.

**Comment by cyborg5** [comment]
I don't see anything in that error message to indicate a problem with IRLib itself. It looks to me like it's as it says an internal compiler error. I'm sorry I won't be able to help you with it. They have a link that tells you how to submit a bug report so I suggest you try that.
