### ISSUE TITLE
Arduino Air conditioner Remote Controller

### ISSUE THREAD

**Issue by krazbali** [cyborg5/IRLib2#31]
With the normal ir decode dumb.ino I just got 0 or 0xFFFFFFFF as value, but with hashDecode.ino I got 2 codes, when I pressed one button. First is the header, its constant, but the second code is depend on the button (function). 
Serial monitor (power on button):
Unknown protocol. Hash value is: 0x811C9DC5
Unknownprotocol. Hash value is: 0x39FCE14C

The problem is I can't replay this codes...

**Comment by cyborg5** [comment]
Most air conditioner codes are extremely long. You might need to increase the buffer size. Look in IRLibGlobals.h for the line

**Comment by hectorlee** [comment]
Is there a buf length setting for sending with the rawSend sketch? The rawSend sketch isn't sending the full length of the ir code for a hitachi air conditioner remote but sends shorter codes just fine.

**Comment by lrrrrr** [comment]
I am having the same issue as hectorlee. The length of my signal is 292, but rawSend sketch sends a much shorter signal.

**Comment by lrrrrr** [comment]
Actually, there is an open pull request by alexalexein which resolves this. Successfully controlling a Mitsubishi air conditioner after implementing it.

**Comment by cyborg5** [comment]
Because air-conditioners use extremely long sequences that are difficult to encode efficiently we will not be supporting air conditioner protocols.
