### ISSUE TITLE
SAMD51 compile Errors

### ISSUE THREAD

**Issue by MrBryonMiller** [cyborg5/IRLib2#54]
Latest Library has compile errors when targeted to my AdaFruit Metro M4.  Looks like IRHardware.h is missing SAMD51 updates.  I edited my copy and was able to get a good compile and receiver test.  

I'm sure you have a working version and I'm sure my version would have little value to you, especially since I was guessing a lot.  When you get it updated I'd be happy to test for receive as well as transmit.

Bryon

**Comment by cyborg5** [comment]
So sorry about that. Forgot to include the updated file in the last commit. It's there now.
