### ISSUE TITLE
IRLibSAMD51.h extern Tcc*  not being accepted by Arduino compiler

### ISSUE THREAD

**Issue by doggo4242** [cyborg5/IRLib2#63]
I used this library in an Arduino project, but it did not compile, error message: 'Tcc' does not name a type
extern Tcc* = IR_TCCx;

If this is a stupid question, I am sorry. I am a total noob, but please tell me how to fix this.

issuewithstuff

**Comment by cyborg5** [comment]
I think I know what the problem is and it's my fault. Give me a day or two. My off-line life is kind of complicated right now. For some reason IRLibSAM51.h is getting included even when you're not using a SAMD51 board.

**Comment by issuewithstuff** [comment]
Ok. Thx.

**Comment by cyborg5** [comment]
Can you give me some more specifics on this error? What type of board were you using when trying to compile? What versions of the Arduino IDE are you using?

**Comment by issuewithstuff** [comment]
Arduino Mega 2560, ide 1.8.6

**Comment by issuewithstuff** [comment]
code attached
[Universal_remote.zip](https://github.com/cyborg5/IRLib2/files/2499329/Universal_remote.zip)

**Comment by issuewithstuff** [comment]
It's been awhile since I started this thread. Has this issue been resolved?

**Comment by cyborg5** [comment]
All support for SAMD 51 and M4 boards has been recently updated. Let me know if you have further issues. SAMD51.txt has details. The main documentation will be updated soon.
