### ISSUE TITLE
Add to Arduino Library Manager?

### ISSUE THREAD

**Issue by dherrada** [cyborg5/IRLib2#88]
It might be easier and quicker for people to install this if they can do it directly from the Arduino IDE. If you do decide to put this on the Library Manager, @ me when it's up there so I can update the Adafruit learn guides that use this to reflect that change.

**Comment by JetForMe** [comment]
@evaherrada This was closed as completed, but the tutorials (e.g. https://learn.adafruit.com/using-an-infrared-library/sending-ir-codes?view=all#overview) still tell me to download the zip file and manually install it.
