### ISSUE TITLE
User complains I'm not responsive enough

### ISSUE THREAD

**Issue by ArminJo** [cyborg5/IRLib2#96]
****

**Comment by ArminJo** [comment]
Consider to use https://github.com/ukw100/IRMP.
See [comparison matrix](https://github.com/ukw100/IRMP#quick-comparison-of-4-arduino-ir-receiving-libraries).

**Comment by cyborg5** [comment]
I might not respond to every issue as quickly as you hope that this is not an abandoned project. I will review your issues and get back to you when I can.

**Comment by ArminJo** [comment]
Hi cyborg5
good to hear that you are still alive and hopefully healthy in these days.
But you must know, that there are many abandoned repos out there.
And please propose a better description for not getting an reaction for more than one year.
Regard Armin
